#!/bin/bash

# Create GitHub issues for Epic 8: SVG Map Integration
# Prerequisite: GitHub CLI (gh) is installed and authenticated

set -e

if ! command -v gh &> /dev/null; then
  echo "GitHub CLI (gh) is not installed. Please install it first."
  exit 1
fi

echo 'Creating Epic 8 issues...'

echo 'Creating US-801: Pruned SVG Base Map (Operational-Only)...'
gh issue create \
  --title "US-801: Pruned SVG Base Map (Operational-Only)" \
  --body "**User Story**\n\nAs a **developer**  \
I want to **prune the base SVG map to only operational stations/lines**  \
So that **rendered tours match the dataset and exclude unbuilt lines**\n\n**Acceptance Criteria**\n\n- [ ] Python script \`scripts/prune_svg_map.py\` reads \`data/raw/Singapore_MRT_and_LRT_System_Map.svg\`\n- [ ] Filters to stations where \`status == operational\` from \`data/raw/stations.csv\`\n- [ ] Uses optional mapping file \`data/processed/svg_name_map.csv\` to resolve label/name mismatches\n- [ ] Removes or hides non-operational stations and segments from the SVG\n- [ ] Writes pruned map to \`data/processed/sg_mrt_lrt_built_only.svg\`\n- [ ] Preserves CC BY-SA 3.0 attribution within repo and in the output SVG metadata\n- [ ] Generates a report/list of unmatched SVG labels for mapping updates\n\n**Story Points:** 5  \
**Priority:** High\n" \
  --label "visualization,svg,phase-1,epic-8,priority-high" \
  --milestone "Epic 8: SVG Map Integration"

echo 'Creating US-802: SVG Name Mapping & Validation...'
gh issue create \
  --title "US-802: SVG Name Mapping & Validation" \
  --body "**User Story**\n\nAs a **developer**  \
I want to **maintain a mapping between SVG labels and station IDs**  \
So that **the pruning and overlay scripts can reliably match stations**\n\n**Acceptance Criteria**\n\n- [ ] Create \`data/processed/svg_name_map.csv\` with columns: \`svg_label,station_id\`\n- [ ] Script \`scripts/validate_svg_mapping.py\` reports missing/ambiguous mappings and unmatched SVG elements\n- [ ] Mapping covers ≥ 95% of operational stations; remaining listed in a TODO section\n- [ ] Document how to update the mapping in \`docs/visualization/svg_map_integration.md\`\n\n**Story Points:** 3  \
**Priority:** Medium\n" \
  --label "visualization,svg,phase-1,epic-8,priority-medium" \
  --milestone "Epic 8: SVG Map Integration"

echo 'Creating US-803: Tour Overlay Renderer (Arrows + Steps)...'
gh issue create \
  --title "US-803: Tour Overlay Renderer (Arrows + Steps)" \
  --body "**User Story**\n\nAs a **user**  \
I want to **render a single TSP tour onto the pruned SVG with directional arrows and step numbers**  \
So that **I can visually follow the route station by station**\n\n**Acceptance Criteria**\n\n- [ ] Python script \`scripts/render_tour_to_svg.py\` accepts: pruned SVG path, ordered tour (station IDs), style options\n- [ ] Draws per-segment paths with arrowheads indicating direction\n- [ ] Places step numbers along the path or at stations; start/end markers included\n- [ ] Outputs static SVG per tour to \`data/processed/maps/<tour_name>.svg\`\n- [ ] Works with tours generated by implemented solvers (NN, 2-opt, SA, GA) via station IDs\n- [ ] Legend and basic styles included; single tour per render\n\n**Story Points:** 8  \
**Priority:** High\n" \
  --label "visualization,svg,phase-1,epic-8,priority-high" \
  --milestone "Epic 8: SVG Map Integration"

echo 'Creating US-804: Export Sample Static SVGs...'
gh issue create \
  --title "US-804: Export Sample Static SVGs" \
  --body "**User Story**\n\nAs a **developer**  \
I want to **export example static SVGs for selected tours**  \
So that **they can be embedded in notebooks/pages immediately**\n\n**Acceptance Criteria**\n\n- [ ] Generate at least one sample tour using an existing solver\n- [ ] Render static SVG to \`data/processed/maps/*.svg\` using the overlay script\n- [ ] Add a short README or doc note with usage and CC BY-SA attribution\n\n**Story Points:** 3  \
**Priority:** Medium\n" \
  --label "visualization,svg,phase-1,epic-8,priority-medium" \
  --milestone "Epic 8: SVG Map Integration"

echo "\n✓ Epic 8 issues created."
